/*
    Type:       Test class
    Purpose:    Tests the class PortalQuickLinks_Controller
    ---------------------------------------------------------------
    History:

    25-Feb-2014 N Patterson    Created
*/
@isTest
private class PortalQuickLinks_Controller_Test {

    public static TestMethod void testMe() {
        PortalQuickLinks_Controller c = new PortalQuickLinks_Controller();
        
    }
}