public with sharing class PortalQuickLinks_Controller extends PortalPageWithAccounts_Virtual_Con {

/*
    Type:       Controller
    Purpose:    Controller to display quick links

    Used By:    PortalQuickLinks component
    ---------------------------------------------------------------
    History:

    18-Feb-2011 D.Thong (Salesforce)    Created
    25-Feb-2014 N.Patterson   			Moving test methods to a test class to reduce code usage

*/

    /* CONSTRUCTOR */
    public PortalQuickLinks_Controller() {
        
    }
    
    

}